---
title: "PowerPuffGenes Report"
authors: "FN, CV, LP"
date: "2025-04-18"
output:
  github_document:
    toc: true
  pdf_document:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(GenomicRanges)
library(IRanges)
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(purrr)
library(magrittr)
library(pheatmap)
library(textshape)
library(Rcpp)
library(DESeq2)
library(stringr)
```


#### Approach:

#### Parameter and path definition
```{r define variables}
RESULT_PATH       <- "../result_human"

```

```{r load data}
# loading RNAseq results from 06_Differential_expression_analyses
load(file.path(RESULT_PATH, "ATAC_gene_promoter.RData"))

# loading counts and tpm
load(file.path(RESULT_PATH, "DESeq2_results.RData"))
load(file.path(RESULT_PATH, "TPM_results.RData"))

# loading prolonged gene list
genes_of_interest <- read.csv(file.path(RESULT_PATH, "prolonged_gene_list.csv"), header = TRUE)

```

```{r dox and non-dox unique peak overalp gene promoters, dependson="previous_chunk"}
# Now find same gene_id in RNAseq resuts
# filter significant genes from RNAseq "filtered_results" to non-dox promoter overlaps
sig_rnaseq_atac_non_dox <- non_dox_gene_promoter_ov[non_dox_gene_promoter_ov$gene_id %in% filtered_results$gene_id]

print(c("this is how many genes overlap between RNAseq and ATACseq non-dox peaks", length(sig_rnaseq_atac_non_dox)))

# filter significant genes from RNAseq "filtered_results" to dox promoter overlaps
sig_rnaseq_atac_dox <- dox_gene_promoter_ov[dox_gene_promoter_ov$gene_id %in% filtered_results$gene_id]

print(c("this is how many genes overlap between RNAseq and ATACseq dox peaks", length(sig_rnaseq_atac_dox)))

# filter significant genes from RNAseq "filtered_results" to dox, non-dox promoter overlaps
sig_rnaseq_atac_dox_non_dox <- dox_non_dox_gene_promoter_ov[dox_non_dox_gene_promoter_ov$gene_id %in% filtered_results$gene_id]

print(c("this is how many significant genes overlap between RNAseq and ATACseq dox, non-dox peaks", length(sig_rnaseq_atac_dox_non_dox)))
```

```{r matching peaks wirh prolonged genes RNAseq}
# filter upregulated-prolonged genes to dox promoter overlaps
up_genes <- genes_of_interest %>%
  filter(tpm_log2fc > 0)
print(c("this is how many upregulated genes with dox", length(up_genes$gene_name)))
up_prolonged_rnaseq_atac_dox <- dox_gene_promoter_ov[dox_gene_promoter_ov$gene_name %in% up_genes$gene_name]
up_atac_genes <- up_genes %>%
  filter(gene_name %in% up_prolonged_rnaseq_atac_dox$gene_name)

print(c("this is how many genes overlap between upregulated-prolonged RNAseq genes and ATACseq dox peaks", length(up_prolonged_rnaseq_atac_dox)))

# save data
write.csv(up_atac_genes, file.path(RESULT_PATH,"up_atac_genes.csv"), row.names = FALSE)

# filter doenregulated-prolonged genes to dox promoter overlaps
down_genes <- genes_of_interest %>%
  filter(tpm_log2fc < 0)
print(c("this is how many downregulated genes with dox", length(down_genes$gene_name)))
down_prolonged_rnaseq_atac_dox <- dox_gene_promoter_ov[dox_gene_promoter_ov$gene_name %in% down_genes$gene_name]
down_atac_genes <- down_genes %>%
  filter(!(gene_name %in% down_prolonged_rnaseq_atac_dox$gene_name))

print(c("this is how many genes overlap between downregulated-prolonged RNAseq genes and ATACseq dox peaks", length(down_prolonged_rnaseq_atac_dox)))

# save data
write.csv(down_atac_genes, file.path(RESULT_PATH,"down_atac_genes.csv"), row.names = FALSE)
```


```{r}

# filter significant genes from RNAseq all tpm results to dox, non-dox promoter overlaps
rnaseq_atac_dox_non_dox <- tpm_filtered[rownames(tpm_filtered) %in% dox_non_dox_gene_promoter_ov$gene_id,]

print("TPM summary for genes with ATAC peak")
print(summary(rnaseq_atac_dox_non_dox))

# filter significant genes from RNAseq all tpm results to dox, non-dox promoter overlaps
rnaseq_no_atac_dox_non_dox <- tpm_filtered[!(rownames(tpm_filtered) %in% dox_non_dox_gene_promoter_ov$gene_id),]

print("TPM summary for genes without ATAC peak")
print(summary(rnaseq_no_atac_dox_non_dox))

```

```{r}

sig_genes_with_peaks <- sig_rnaseq_atac_dox_non_dox$gene_name
time_points <- names(avg_and_sd_values)[grep("avg", names(avg_and_sd_values))]

tpm_sig_genes_with_peaks <- avg_and_sd_values[avg_and_sd_values$gene_name %in% sig_rnaseq_atac_dox_non_dox$gene_name, ]
tpm_sig_genes_with_peaks$gene_name <- NULL

tpm_sig_genes_without_peaks <- avg_and_sd_values[!(avg_and_sd_values$gene_name %in% sig_rnaseq_atac_dox_non_dox$gene_name), ]
tpm_sig_genes_without_peaks$gene_name <- NULL

pivot_with_peaks <- tpm_sig_genes_with_peaks %>% 
  pivot_longer(cols = all_of(time_points), names_to = 'Time', values_to = 'TPM')
print(mean(pivot_with_peaks$TPM))

pivot_without_peaks <- tpm_sig_genes_without_peaks %>% 
  pivot_longer(cols = all_of(time_points), names_to = 'Time', values_to = 'TPM')
print(mean(pivot_without_peaks$TPM))

ggplot(pivot_with_peaks, aes(x = TPM)) +
  geom_histogram(bins = 50) +
  facet_wrap(~ Time, scales = "free_x")+
  xlim(0,200) +
  ylim(0,200) +
  theme("paperwhite")

ggplot(pivot_without_peaks, aes(x = TPM)) +
  geom_histogram(bins = 50) +
  facet_wrap(~ Time, scales = "free_x")+
  xlim(0,200) +
  ylim(0,200) +
  theme("paperwhite")

summary(tpm_sig_genes_with_peaks)

```
